### ISSUE TITLE
Error in XML files

### ISSUE THREAD

**Issue by BolunDai0216** [unitreerobotics/unitree_mujoco#1]
Hi,

I think there is an error in the XML files. 

In the sensors for `framepos` and `framequat`, the `objtype` is all set to `site`. I think it should be `"site"` instead, i.e., changing from
```
<framepos name="Body_Pos" objtype=site objname="imu"/>
<framequat name="Body_Quat" objtype=site objname="imu"/>
```
to
```
<framepos name="Body_Pos" objtype="site" objname="imu"/>
<framequat name="Body_Quat" objtype="site" objname="imu"/>
```

After this change, I was able to start the MuJoCo simulation in MuJoCo 2.13. Otherwise, it would give me 
```
Error=XML_ERROR_PARSING_ATTRIBUTE ErrorID=7 (0x7) Line number=183: XMLElement name=framepos
```

I am not sure this is the case for other MuJoCo versions.

**Comment by TrivasZhang** [comment]
Thanks, I will try it.
