### ISSUE TITLE
Support for high-level control in sim

### ISSUE THREAD

**Issue by RayYoh** [unitreerobotics/unitree_mujoco#9]
Hi, thanks for your work. Does current version just supports low-level control? I have tried the high-level control code in [unitree_sdk2_python, sportmode_test](https://github.com/unitreerobotics/unitree_sdk2_python/blob/master/example/high_level/sportmode_test.py), it occurs error.

**Comment by wuyangning** [comment]
You are right. 
Unitree mujoco is mainly provided to users for sim to real verification of their control algorithms, so current version only provides basic support of: 
- sensor data (IMU, joint position, joint velocity).
- wireless controller (Simulate using an Xbox controller).
- motor control.

**Comment by wuyangning** [comment]
> Hi, thanks for your work. Does current version just supports low-level control? I have tried the high-level control code in [unitree_sdk2_python, sportmode_test](https://github.com/unitreerobotics/unitree_sdk2_python/blob/master/example/high_level/sportmode_test.py), it occurs error.

You are right. 
Unitree mujoco is mainly provided to users for sim to real verification of their control algorithms, so current version only provides basic support of: 
- sensor data (IMU, joint position, joint velocity).
- wireless controller (Simulate using an Xbox controller).
- motor control.
